### ISSUE TITLE
Client focus being transferred during runtime

### ISSUE THREAD

**Issue by kThisIsCvpv** [powerbot/RSBot-API#2114] opened 2019-12-16 15:00 UTC
Client focus is being transferred when the script is being run even though input is disabled.

**Example 1:**
I start script.
I switch to another window. Client "loses" focus (it shouldn't, script has control).
Script clicks, client re-enters focus.

**Example 2:**
Script defocuses.
I tab back in. Client "regains" focus (it shouldn't, script has control).

I'm guessing that the internals do not check whether or not a script is enabled and input is disabled.

**Comment by Paris** [comment] 2020-05-25 19:00
Duplicate of #1447.

**Closed by Paris** 2020-05-25 19:00 UTC
Labels: bug, gui
