### ISSUE TITLE
Widget issues after update (inventory, chat, trade)

### ISSUE THREAD

**Issue by iicryptic** [powerbot/RSBot-API#2073] opened 2019-07-18 20:47 UTC
![image](https://user-images.githubusercontent.com/52004949/61490693-91945600-a97b-11e9-94ba-0722da3e9bf1.png)

This causes issues with trying to select menu options.

Noticed this with Widget(219, 1)

**Comment by tanlines** [comment] 2019-07-19 00:03
To add to this, inventory bounds are also off.

https://cdn.discordapp.com/attachments/343174846584193024/601548690435604491/unknown.png

**Comment by ChrisBPB** [comment] 2019-07-20 10:02
potentially the bots overlay is off center, but the forum post states clearing the cache fixes it?

**Comment by ChrisBPB** [comment] 2019-07-20 10:11
is there something you do prior to this that makes it break? I am unable to reproduce

https://i.imgur.com/ewbLK92.png

**Comment by drusepth** [comment] 2019-07-20 22:23
Even after clearing cache, I'm still seeing the item overlays off-center with the view display, and actions in scripts to e.g. click on an item frequently miss (by clicking to the left of the bounds), so it doesn't seem to just be a display issue.

**Comment by ChrisBPB** [comment] 2019-07-21 07:07
what os?

**Comment by drusepth** [comment] 2019-07-21 17:05
Windows 10

**Comment by miketerpak** [comment] 2019-07-21 18:36
I reported a similar issue in the forums regarding the trade screen. There, I posted that I suspected it was to do with the jagexcache because at first, deleting it completely would bring the first trade window widget back to the correct place. But, when I tried recreating this the next day, the issue moved to the 2nd trade window and clearing the cache did not help. Since then, I've seen both trade screens and the minimap widget displaced without much consistency of when each widget moves.

I was scripting and testing heavily for 5 or so days prior with absolutely no problems. For me, the issue began a few days ago, thought I don't remember exactly which day. But since then, every time I log in, some widget is out of place.

I tried on my Windows 10 desktop and laptop, as well as an Ubuntu 16.04 VM. Ubuntu also had a displaced 2nd trade screen widget, and was a fresh install with jre1.8 and only the RSBot JAR (no scripts).

**Comment by miketerpak** [comment] 2019-07-21 18:56
Also, not sure if the way RSBot is written makes this relevant, but I tried both the exe and jar on windows 10, no difference.

**Comment by ChrisBPB** [comment] 2019-07-22 08:59
ok so the problem with this is that the inventory is handled differently normally compared to when you have the bank or GE open, the items do not have individual widgets

will have to change the math for this I suppose

**Comment by AshGreh** [comment] 2019-07-22 12:23
@ChrisBPB screenPoint is off ( look at chat for an example, current offset is by -20, -23 iirc ).

**Comment by ChrisBPB** [comment] 2019-07-23 17:56
not sure what would cause some to be correct and some now as these are just read from the hook but I will see if I can find anything

**Comment by AshGreh** [comment] 2019-07-24 05:39
Let's temporarily patch the issue with off sets for inventory and chat and work on a proper fix after, as the client has had this issue for over a week now. I will help you investigate the actual issue later.

**Comment by ChrisBPB** [comment] 2019-07-25 07:38
temp fix for inventory https://github.com/powerbot/powerbot/commit/4cbc818515b0f27bc769e231675cf6ea2b76eb90

**Comment by AshGreh** [comment] 2019-07-25 07:41
@ChrisBPB could you use variable offsets instead?
final int x = base.x -3 + OFFSET_X...
So that we can easily work around the changes when a proper patch can be made

**Comment by AshGreh** [comment] 2019-07-27 08:11
@Paris I only fixed inventory. ScreenPoint still needs a fix.

**Comment by ChrisBPB** [comment] 2019-07-30 10:43
this should fix it for fixed size
https://github.com/powerbot/powerbot/commit/d0fa777ec6f74beb9c3ed9f2e90200ba743fa5bc

struggling to figure out resizable currently

**Comment by Paris** [comment] 2019-12-07 08:21
Merged into #2083.

**Closed by Paris** 2019-12-07 08:21 UTC
Labels: bug, gui
